# Generated by Django 4.1.5 on 2023-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='machine', through='card_portal.MachinePermittedEmployee', to='card_portal.employee'),
        ),
    ]
