# Generated by Django 4.1.5 on 2023-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='country',
        ),
    ]
