# Generated by Django 4.1.5 on 2023-01-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0002_remove_employees_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media/employees/images/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_portal.employees')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
