# Generated by Django 4.1.5 on 2023-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0003_employeesimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesimage',
            name='image',
            field=models.ImageField(upload_to='employees/images/'),
        ),
    ]
