# Generated by Django 4.1.5 on 2023-05-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0005_employeesdailyattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
