# Generated by Django 4.1.5 on 2023-05-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0006_rename_employees_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachinePermittedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_portal.employee')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_portal.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='employee',
            field=models.ManyToManyField(related_name='employee', through='card_portal.MachinePermittedEmployee', to='card_portal.employee'),
        ),
    ]
