# Generated by Django 4.1.5 on 2023-05-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0007_machine_machinepermittedemployee_machine_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='employee',
            field=models.ManyToManyField(related_name='machine', through='card_portal.MachinePermittedEmployee', to='card_portal.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeAccessCardUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('access_type', models.CharField(choices=[('Sign In', 'Sign In'), ('Sign Out', 'Sign Out')], max_length=255)),
                ('time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card_portal.employee')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card_portal.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
