# Generated by Django 4.1.5 on 2023-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0008_alter_machine_employee_employeeaccesscardusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccesscardusagelog',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
