# Generated by Django 4.1.5 on 2023-05-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_portal', '0010_employeesdailyattendance_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccesscardusagelog',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card_portal.machine'),
        ),
    ]
