# Generated by Django 4.1.5 on 2023-05-12 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card_portal', '0011_alter_employeeaccesscardusagelog_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
